#! /bin/bash

echo "Zork1 or Zork2 or Zork3"

read zorkversion

if [ "$zorkversion" = "zork1" ]; then
	bash zork1
elif [ "$zorkversion" = "zork2" ]; then
	bash zork2
elif [ "$zorkversion" = "zork3" ]; then
	bash zork3
else
		echo "NO VALID INPUT"
fi
