#!/bin/bash

echo Baldurs Gate 1 or 2

case $1 in
		1)
				/home/ari/GOG\ Games/Baldurs\ Gate\ Enhanced\ Edition/start.sh
				;;
		2)
				/home/ari/GOG\ Games/Baldurs\ Gate\ 2\ Enhanced\ Edition/start.sh
				;;
		*)
				echo
				echo failed input error
				echo please provide argument 1 or 2
				;;
esac
