#!/bin/bash

clear
games=( '1.bald1' '2.bald2' '3.deadcells' '4.dungeons2' '5.gungeon' '6.icon' '7.neverwinter' '8.stardew' )

echo -e "\e[92m---Options---\e[0m"
for element in "${games[@]}"
do
    echo -e "\e[92m: \e[91m$element\e[0m"
done
echo -e "\e[92m-------------\e[0m"

read -p "Game: " game
lower=${game,,}

case $lower in
    1|bald1)
        /home/ari/GOG\ Games/Baldurs\ Gate\ Enhanced\ Edition/start.sh
        ;;
    2|bald2)
        /home/ari/GOG\ Games/Baldurs\ Gate\ 2\ Enhanced\ Edition/start.sh
        ;;
    3|deadcells)
        /home/ari/GOG\ Games/Dead\ Cells/start.sh
        ;;
    4|dungeons2)
        /home/ari/GOG\ Games/Dungeons\ 2/start.sh
        ;;
    5|gungeon)
        /home/ari/GOG\ Games/Enter\ the\ Gungeon/start.sh
        ;;
    6|icon)
        /home/ari/GOG\ Games/Iconoclasts/start.sh
        ;;
    7|neverwinter)
        /home/ari/GOG\ Games/Neverwinter\ Nights\ Enhanced\ Edition/start.sh
        ;;
    8|stardew)
        /home/ari/GOG\ Games/Stardew\ Valley/start.sh
        ;;
	exit)
		exit
		;;
    *)
		echo
        echo -e "\e[31mfailed input error\e[0m"
		echo
        ;;
esac
