#!/bin/bash

mounttype=( 'physical' 'network' 'umount' )

echo "----------"
for element in "${mounttype[@]}"
do
	echo ": $element"
done
echo "----------"

read -p "Type: " mtype
lower=${mtype,,}

case $lower in
	physical)
		read -p 'Device ID: ' id
		read -p 'Mount Point: ' mount
		sudo mount $id $mount
		;;
	network)
		read -p 'ip: ' ip
		read -p 'foler: ' folder
		read -p 'username: ' username
		read -p 'password: ' -s password
		sudo mount -t cifs \\\\$ip\\$folder /mnt/network -o username=$username,password=$password,uid=1000,gid=999
		;;
	umount)
		read -p 'Unmount What: ' dev
		sudo umount $dev
		;;
	*)
		echo Input Error
		;;
esac
