#!/bin/bash

case $1 in
		mount)
				echo 'ip:'
				read ip
				echo 'folder:'
				read folder
				echo 'username:'
				read username
				echo 'password:'
				read password
				sudo mount -t cifs \\\\$ip\\$folder /mnt/network -o username=$username,password=$password
				;;
		umount)
				sudo umount /mnt/network
				;;
		*)
				echo Input Error
				echo 'Options : mount | umount'
				;;
esac
